name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [ amd64, arm64 ]
        variant: [ imagebuilder, kernelbuilder ]
        platform: [ qemu, lima ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Build the image
        run: ./build ${{ matrix.variant}}-${{ matrix.platform}}-${{ matrix.arch }}
      - name: Upload debian ${{ matrix.arch }} image
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.variant}}-${{ matrix.platform}}-${{ matrix.arch }}
          path: |
            .build/${{ matrix.variant}}-${{ matrix.platform}}-${{ matrix.arch }}-trixie-*.qcow2
            .build/${{ matrix.variant}}-${{ matrix.platform}}-${{ matrix.arch }}-trixie-*.raw
          if-no-files-found: ignore
          retention-days: 3
